const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Syed Arshad";
const email = "Email";
const emailHint = "abcd@gmail.com";
const password = "Password";
const passwordHint = "******";
const forgetPassword = "Forgot password?";
const retypePassword = "Confirm Password";
const name = "Name";
const nameHint = "Syed Arshad";
const login = "Login";
const signup = 'Sign Up';
const createNewAccount = "or, create a new account";
const loginwith = 'Login with';
const privacyPolicy = "Privacy Policy";
const termsAndConditions = "Terms and conditions";
const alreadyHaveAccount = "Already have an account? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

const searchAnything = "Search for anything",
    todaysDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSeller = "Top Seller",
    topCategories = "Top Categories",
    brand = "Brand",
    featuredProduct = "Featured Products",
    womenDress = "Women's Dresses",
    girlsWatches = "Girls Wacthes",
    mobilePhones = "Mobile Phones",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredCategories = "Featured Categories";

const womenClothing = "Women Clothing",
    menClothingFashion = "Men's Clothing and Fashion",
    compAccess = "Computer & Accessories",
    automobile = "AutoMobile Accessories",
    kidtoys = "Kid's Toys",
    sports = "Sports",
    jewelry = "Jewelry",
    cellphone = "Cellphone & Tablets",
    furniture = "Furniture";

const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller Policy",
    returnPolicy = "Return Policy",
    productsYouMayLike = "Products you may also like",
    supportPolicy = "Support Policy";
